development:
  adapter: postgresql
  encoding: utf8
  database: postgres_login_app_development # the name of your app
  pool: 5


test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: postgres_login_app_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: postgres_login_app
  pool: 5
